feat: add and update scripts

diff --git a/bin/anime-game-wish-export b/bin/anime-game-wish-export
--- a/bin/anime-game-wish-export
+++ b/bin/anime-game-wish-export
@@ -1,2 +1,23 @@
-#!/bin/sh
-strings "$(find "$HOME/.local/share" / -path "*_Data/webCaches/Cache/Cache_Data/data_2" -print -quit 2>/dev/null)" | grep -o "https://.*/e20190909gacha-v2/.*" | tail -n1 | xclip -sel clip && echo "History link copied to clipboard!"
+#!/bin/bash
+die() {
+	echo >&2 "$*"
+	exit 1
+}
+
+default_directory="$HOME/.local/share/"
+directory="${1:-$default_directory}"
+
+[[ ! -d "$directory" ]] && die "Invalid directory"
+
+file=$(find "$directory" -path "*_Data/webCaches/Cache/Cache_Data/data_2" -print -quit 2>/dev/null)
+
+[[ ! -f "$file" ]] && die "Unable to locate game files"
+
+link=$(strings "$file" | grep -o "https://.*/e20190909gacha-v2/.*" | tail -n1)
+
+if [[ -n "$link" ]]; then
+	echo "$link" | xclip -sel clip
+	echo "Wish History link was successfully copied to the clipboard!"
+else
+	die "Unable to get Wish History link"
+fi
